name: Test Deno Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.10.2]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Format Deno Module
        run: deno fmt --check
      - name: Build Deno Module
        run: deno run --reload --unstable -A mod.ts
      - name: Test Deno Module
        run: deno test --allow-none --unstable -A
